# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: source
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown  #define which markdown you wanna to use for your site.
highlighter : pygments  #define which lighlighter you wanna to use for your code section.


# SEO settings
title: Xuna Xu
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"

# Site settings
url: http://xunaxu.github.io
baseurl: "/Jekyll-Iris"
paginate_path: /page:num
gems: [jekyll-paginate]
paginate: 2


# Dynamic Text on the Header 
dynamic-typing: true
shuffle: true # Shuffle the lines.
loop: true
loop-count: false # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # Keep the <span> attribute on!
  - text: "<span>The best preparation for tomorrow is doing your best today.</span>"
  - text: "<span>without documentation and test cases, your master pecie is not only your own graveyard, but also bury whoever comes cross. - xunaxu</span>"



# Author settings
author:
  name      : Xuna Xu
  job       : Software Engineer
  email     : 78756e61@gmail.com
  url       : http://xunaxu.github.io
  github    : http://github.com/xunaxu
  twitter   : http://twitter.com/xuna_x
  linkedin  : https://au.linkedin.com/in/xuna-xu-8a135094
  avatar    : /assets/images/avatar.JPG

# google analytics
google_analytics: UA-819232-** #### REPLACE ME, register your google analytics account if you don't have one ####
#repo: http://github.com/xunaxu/jekyll-iris

# comments
comments: true 
disqus_shortname: "xunaxu" #### REPLACE ME, register your account at disqus if you don't have one ####

# subscribe
subscribe: true  
#### REPLACE SUBSCRIBE.HTML in source/_includes, so you can put your own mail chimps subscribe form in####

#share
email-share: true
fb-share: true
twitter-share: true
linkedin-share: true
reddit-share: false
google-plus-share: true
tumblr-share: false
pinterest-share: false
